### ISSUE TITLE
Add margin right to file input

### ISSUE THREAD

**Issue by MatheusRich** [MatheusRich/dontfile#51]
In some languages (like portuguese), the file input text gets too close of file icon. A `margin-right` should do the job.

![image](https://user-images.githubusercontent.com/20938712/45639550-b5022200-ba86-11e8-8fd9-f316a5a66987.png)

**Comment by VzqzAc** [comment]
Hey @MatheusRich I'm organizing a hackday at my company this weekend, and I think this is a good issue for some of our interns, do you mind if I hold this to tackle it on Saturday?

**Comment by MatheusRich** [comment]
@VzqzAc That's ok! You guys can assign any issue you want to! Thanks for your contribution!

**Comment by VzqzAc** [comment]
Hey @MatheusRich! @DanielISC just submitted the PR for the changes, we paired to ensure the fix was properly applied, let him know about any issue you may have :) we may keep contributing today, thanks!
