### ISSUE TITLE
Update Docker to Ruby 2.5.1 and Rails 5.2.1

### ISSUE THREAD

**Issue by MatheusRich** [MatheusRich/dontfile#58]
Since Dontfile has updated its dependencies, the Dockerfile must be upgraded too.

**Comment by MatheusRich** [comment]
Maybe some error could happen after using the 2.5.1 image of ruby. Would be nice if you check them.

**Comment by peterjgrainger** [comment]
Yep, will do just wanted to check. I'll do this one then

**Comment by MatheusRich** [comment]
Closed via #67
