### ISSUE TITLE
Download page content

### ISSUE THREAD

**Issue by MatheusRich** [MatheusRich/dontfile#59]
Adding a `.zip` on the URL (like `dontfile.com/my-page.zip`), Dontfile must download the page content (as .txt) and the file on a zip. We can use the rubyzip gem to achieve this!

**Comment by wilbertliu** [comment]
Hello @MatheusRich 👋🏻,

Love this project! May I work on this issue? Will send a PR and refer
this issue 🙂

**Comment by MatheusRich** [comment]
@wilbertliu It's yours! Thank you!

**Comment by MatheusRich** [comment]
@wilbertliu If you want to take a look, [dontpad](dontpad.com) has this feature too!

**Comment by wilbertliu** [comment]
@MatheusRich That would be nice, Matheus! But I think the link is incorrect, no? 🤔

**Comment by MatheusRich** [comment]
It's okay to me :disappointed:. Anyway, its http://www.dontpad.com

**Comment by wilbertliu** [comment]
Sure, no problem at all! 😉

Sincerely,
Wilbert Liu

**Comment by MatheusRich** [comment]
Closed via #68

**Comment by MatheusRich** [comment]
Closed via #68
