### ISSUE TITLE
Change icon based on file type

### ISSUE THREAD

**Issue by MatheusRich** [MatheusRich/dontfile#60]
The icon for an uploaded file can be different based on the file type. I think 5 icons may be sufficient to this.

* Images: `<i class="far fa-file-image"></i>`
* PDFs: `<i class="far fa-file-pdf"></i>`
* Videos: `<i class="far fa-file-video"></i>`
* Zip:`<i class="far fa-file-archive"></i>`
* Default: `<i class="far fa-file-alt"></i>` (it's the current icon)

**Comment by ozmar-11** [comment]
can I take this one?
